#!/usr/bin/ruby

# -------------------------------------------------------------------------- #
# Copyright 2002-2018, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

t0 = Time.now
require_relative 'lib/lxd_driver'

LXDriver.log_init

vm_name = ARGV[0]
mac = ARGV[1]
bridge = ARGV[2]
model = ARGV[3]
net_drv = ARGV[4]
host_nic = ARGV[5]
vm_id = ARGV[6]
host = ARGV[7]

info = LXDriver.action_xml
nics = info.multiple_elements('NIC')
nic_info = info.device_info(nics, 'NIC', mac)

client = LXDClient.new
container = Container.get(vm_name, client)

container.devices.update(info.nic(nic_info))
container.update

LXDriver.log_end(t0)
