#!/usr/bin/ruby

# -------------------------------------------------------------------------- #
# Copyright 2002-2018, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

$LOAD_PATH.unshift File.dirname(__FILE__)

t0 = Time.now
require 'lxd_driver'
require 'base64'

LXDriver.log_init

vm_name = ARGV[0]
image_path = ARGV[1]
target = ARGV[2]
disk_index = ARGV[3]
xml = ARGV[4]
vm_id = ARGV[5]

# xml creation
info = LXDriver.action_xml(Base64.decode64(xml))
disks = info.multiple_elements('DISK')
disk_info = info.device_info(disks, 'DISK', target)

# post_process
disk_hash = info.disk(disk_info)

client = LXDClient.new
container = Container.get(vm_name, client)

# mount and container disk creation
source = disk_hash.values[0]['source']
device = LXDriver.device_path(info, disk_info)
mapper = LXDriver.select_driver(disk_info)
mapper.run('map', source, device)

container.devices.update(disk_hash)
container.update

LXDriver.log_end(t0)
