#!/usr/bin/ruby

# -------------------------------------------------------------------------- #
# Copyright 2002-2018, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

$LOAD_PATH.unshift File.dirname(__FILE__)

t0 = Time.now
require 'lxd_driver'

LXDriver.log_init

xml_path = ARGV[0]
vm_id = ARGV[2]

xml = STDIN.read
info = LXDriver::XML.new(xml)
client = LXDClient.new

yaml = LXDriver::YAML.new(info)
container = Container.new(yaml, client)
LXDriver.container_create(container, client)

if info.wild
    container.start
else
    LXDriver.container_storage(info, 'map')
    LXDriver.container_start(container, info)
end

container.config.update('user.xml' => xml)
container.update

LXDriver.vnc(info)
LXDriver.log_end(t0)

puts container.name
