#!/usr/bin/ruby

# -------------------------------------------------------------------------- #
# Copyright 2002-2018, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

$LOAD_PATH.unshift File.dirname(__FILE__)

t0 = Time.now
require 'lxd_driver'

LXDriver.log_init

vm_name = ARGV[0]
mac = ARGV[1]
vm_id = ARGV[2]
host = ARGV[3]

client = LXDClient.new
container = Container.get(vm_name, client)

def detect_nic(devices, mac)
    devices.each do |device, config|
        if device.include?('eth')
            return device if config['hwaddr'] == mac
        end
    end
end

container.devices.delete(detect_nic(container.devices, mac))
container.update

LXDriver.log_end(t0)
