#!/usr/bin/ruby

# -------------------------------------------------------------------------- #
# Copyright 2002-2018, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

t0 = Time.now
require_relative 'lib/lxd_driver'
require 'base64'

LXDriver.log_init

vm_name = ARGV[0]
image_path = ARGV[1]
target = ARGV[2]
disk_index = ARGV[3]
vm_id = ARGV[4]
vm_name = 'one-' + vm_id

info = LXDriver.action_xml
disks = info.multiple_elements('DISK')
disk_info = info.device_info(disks, 'DISK', target)

client = LXDClient.new
container = Container.get(vm_name, client)

mount = container.devices.delete('disk' + disk_info['DISK_ID'])['source']
container.update

mapper = LXDriver.select_driver(disk_info)
mapper.run('unmap', mount)

LXDriver.log_end(t0)
